### ISSUE TITLE
New requirements?

### ISSUE THREAD

**Issue by AceHack** [GoogleCloudPlatform/spark-on-k8s-operator#648] opened 2019-10-02 22:17 UTC
I'm getting the following errors now in v1beta2

spec.driver.cores in body should be greater than or equal to 1
spec.monitoring.prometheus.port in body should be greater than or equal to 49151

Why does cores for the driver have to be greater than or equal to 1?
Also why does the prometheus port have to be greater than or equal to 49151, your sample does not work because it uses a smaller port.

**Comment by liyinan926** [comment] 2019-10-02 22:24
Yes, we changed the type of `spec.driver.cores` from `float32` to `int32` because `spark.driver.cores` is an integer property. The minimum requirement on `spec.monitoring.prometheus.port` is caused by a typo in the JSON validation tag. Will fix that.

**Comment by liyinan926** [comment] 2019-10-02 22:46
The typo for `spec.monitoring.prometheus.port` has been fixed. The port is expected to be between 1024 and 49151.

**Comment by liyinan926** [comment] 2019-10-04 20:52
Actually someone already added `spark.kubernetes.driver.request.cores` into Spark, which will be available in Spark 3.0. Once 3.0 gets releases, we will add a new optional field for that.

**Comment by liyinan926** [comment] 2019-10-04 20:52
Closing this and feel free to reopen or create a new one if you have more questions.

**Closed by liyinan926** 2019-10-04 20:52 UTC
