### ISSUE TITLE
[defect] install sparkoperator by helm failed with unknown field "annotations"

### ISSUE THREAD

**Issue by mstiunicon** [GoogleCloudPlatform/spark-on-k8s-operator#741] opened 2019-12-17 03:06 UTC
I want to install sparkoperator  in IBM cloud, but failed with unknown field "annotations"
Steps:
1) login IBM cloud
`ibmcloud login -a cloud.ibm.com -r us-south -g Metering --sso -u xxxxx@cn.ibm.com`
2) check kubernets
```
PS C:\workspace_go> kubectl version --short
Client Version: v1.16.2
Server Version: v1.16.3+IKS
PS C:\workspace_go> kubectl cluster-info
Kubernetes master is running at https://xxx.us-south.containers.cloud.ibm.com:20089
CoreDNS is running at https://xxx.us-south.containers.cloud.ibm.com:20089/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
kubernetes-dashboard is running at https://xxx.us-south.containers.cloud.ibm.com:20089/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy
Metrics-server is running at https://xxx.us-south.containers.cloud.ibm.com:20089/api/v1/namespaces/kube-system/services/https:metrics-server:/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
PS C:\workspace_go>
```
3) install sparkoperator  by helm

```
PS C:\workspace_go> helm repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator
"incubator" has been added to your repositories
PS C:\workspace_go> helm install incubator/sparkoperator --namespace spark-operator --set sparkJobNamespace=default --generate-name
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(CustomResourceDefinition): unknown field "annotations" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinition
PS C:\workspace_go>
PS C:\workspace_go> kubectl delete CustomResourceDefinition -l app.kubernetes.io/name=sparkoperator
customresourcedefinition.apiextensions.k8s.io "scheduledsparkapplications.sparkoperator.k8s.io" deleted
customresourcedefinition.apiextensions.k8s.io "sparkapplications.sparkoperator.k8s.io" deleted
PS C:\workspace_go>
PS C:\workspace_go> helm install incubator/sparkoperator --namespace spark-operator --set sparkJobNamespace=default --generate-name
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(CustomResourceDefinition): unknown field "annotations" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinition
PS C:\workspace_go>
```

Errors:
1) installing failed by: 
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(CustomResourceDefinition): unknown field "annotations" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinition

I searched keyword "annotations" by google, and also in the repository "spark-on-k8s-operator", no such error, so I submit a defect, hope any helps

Thanks

**Comment by donmstewart** [comment] 2019-12-17 17:18
I also got the same error today as well: -

```helm install incubator/sparkoperator --namespace spark-operator --set sparkJobNamespace=default --generate-name
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(CustomResourceDefinition): unknown field "annotations" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinition```

**Comment by liyinan926** [comment] 2019-12-17 17:36
This seems caused by this commit: https://github.com/helm/charts/commit/0f5eef548a24e49376ebdd249af322bb5ed47531. There's a wrong indention for the field `annotations` in the cloned CRD manifest under the new `crds` folder. Will fix that.

**Comment by liyinan926** [comment] 2019-12-17 17:42
Created https://github.com/helm/charts/pull/19654 to fix the issue.

**Comment by liyinan926** [comment] 2019-12-17 17:50
The fix has been merged. The new version of the Chart is `0.6.1`. Please give it a try. Thanks!

**Comment by mstiunicon** [comment] 2019-12-18 02:54
Not sure whether the installation was successful, cause there is an error message.
```
PS C:\workspace_go> helm install incubator/sparkoperator --namespace spark-operator --set sparkJobNamespace=default --generate-name
Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: kind: CustomResourceDefinition, namespace: , name: scheduledsparkapplications.sparkoperator.k8s.io
PS C:\workspace_go>
PS C:\workspace_go>
PS C:\workspace_go> kubectl delete CustomResourceDefinition sparkapplications.sparkoperator.k8s.io scheduledsparkapplications.sparkoperator.k8s.io
customresourcedefinition.apiextensions.k8s.io "sparkapplications.sparkoperator.k8s.io" deleted
customresourcedefinition.apiextensions.k8s.io "scheduledsparkapplications.sparkoperator.k8s.io" deleted
PS C:\workspace_go>
PS C:\workspace_go>
PS C:\workspace_go>
PS C:\workspace_go> helm install incubator/sparkoperator --namespace spark-operator --set sparkJobNamespace=default --generate-name
Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: kind: CustomResourceDefinition, namespace: , name: sparkapplications.sparkoperator.k8s.io
PS C:\workspace_go>
PS C:\workspace_go> kubectl delete CustomResourceDefinition -l app.kubernetes.io/name=sparkoperator
customresourcedefinition.apiextensions.k8s.io "scheduledsparkapplications.sparkoperator.k8s.io" deleted
customresourcedefinition.apiextensions.k8s.io "sparkapplications.sparkoperator.k8s.io" deleted
PS C:\workspace_go>
PS C:\workspace_go>
PS C:\workspace_go> kubectl delete CustomResourceDefinition sparkapplications.sparkoperator.k8s.io scheduledsparkapplications.sparkoperator.k8s.io
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "sparkapplications.sparkoperator.k8s.io" not found
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "scheduledsparkapplications.sparkoperator.k8s.io" not found
PS C:\workspace_go>
PS C:\workspace_go> helm install incubator/sparkoperator --namespace spark-operator --set sparkJobNamespace=default --generate-name
Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: kind: CustomResourceDefinition, namespace: , name: sparkapplications.sparkoperator.k8s.io
PS C:\workspace_go>
PS C:\workspace_go>
PS C:\workspace_go> helm version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
PS C:\workspace_go> helm list
NAME    NAMESPACE       REVISION        UPDATED STATUS  CHART   APP VERSION
PS C:\workspace_go> helm list -a
NAME    NAMESPACE       REVISION        UPDATED STATUS  CHART   APP VERSION

PS C:\workspace_go> helm inspect chart incubator/sparkoperator
apiVersion: v1
appVersion: v1beta2-1.0.1-2.4.4
description: A Helm chart for Spark on Kubernetes operator
home: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator
keywords:
- spark
maintainers:
- email: yuchaoran2011@gmail.com
  name: yuchaoran2011
name: sparkoperator
version: 0.6.1

PS C:\workspace_go>
```

But I checked the kubernetes dashboard, the Custom Resource Definitions "sparkapplications" and "scheduledsparkapplications" can be found in list
![Snap71](https://user-images.githubusercontent.com/17581823/71051923-be47d600-2184-11ea-84e8-ac350a5c06d3.jpg)
![Snap69](https://user-images.githubusercontent.com/17581823/71051931-c43db700-2184-11ea-8f03-f31fe4818a2b.jpg)
![Snap70](https://user-images.githubusercontent.com/17581823/71051936-cbfd5b80-2184-11ea-90ee-79e38aca4a09.jpg)

**Comment by huineng** [comment] 2019-12-18 11:00
see my conversation in slack https://app.slack.com/client/T09NY5SBT/CALBDHMTL/thread/CALBDHMTL-1576435096.006900

**Comment by mstiunicon** [comment] 2019-12-18 13:33
Looks I can't access the workspace
![Snap72](https://user-images.githubusercontent.com/17581823/71090390-e1eb3a80-21dd-11ea-8ea0-ab650ab052ee.jpg)
would you please invite me (zzwen@cn.ibm.com) to the workspace?

**Comment by huineng** [comment] 2019-12-18 13:40
this is how i solved it 

First I fixed this annotations indent, then i installed with the --skip-crds  flag 
It still installs the crds, so there's a double install of crd in the code giving you this error

**Comment by liyinan926** [comment] 2019-12-18 17:27
See https://github.com/helm/charts/pull/19236.

**Comment by mstiunicon** [comment] 2019-12-19 03:31
@huineng @liyinan926 thanks for help
I have installed sparkoperator successfully with --skip-crds flag

```
PS C:\workspace_go> helm install incubator/sparkoperator --namespace spark-operator --set sparkJobNamespace=default --skip-crds --generate-name
NAME: sparkoperator-1576726158
LAST DEPLOYED: Thu Dec 19 11:29:22 2019
NAMESPACE: spark-operator
STATUS: deployed
REVISION: 1
TEST SUITE: None
PS C:\workspace_go>
```

**Closed** 2019-12-19 03:32 UTC
