### ISSUE TITLE
unable to create ingress (#392) reopen

### ISSUE THREAD

**Issue by aftlabs** [GoogleCloudPlatform/spark-on-k8s-operator#660] opened 2019-10-16 02:21 UTC
$ helm install incubator/sparkoperator \ 
 --name sparkoperator \  
 --namespace spark-operator \ 
 --set enableWebhook=true  \
 --set ingress-url-format="{{$appName}}.ingress.cluster.com"

$> Error: failed parsing --set data: key map "}" has no value

This issue seems resurfacing in my setup. Is there any workaround?

Here are the versions I am using.
Helm:
-- "v2.14.3", GitCommit:"0e7f3b663
K8S:
-- "v1.16.1", GitCommit:"d647ddbd

**Comment by mw-aftab** [comment] 2019-10-16 23:17
This issue is reproducible with Helm vr v2.15.0-rc.2 also.

**Comment by mw-aftab** [comment] 2019-10-16 23:24
I found that a fix was done earlier this year:
[https://github.com/helm/charts/pull/11219/commits/361f452669570377a7843856128d179b2e3eb377]

**Comment by mw-aftab** [comment] 2019-10-17 21:22
digging into the code found out that "pkg/sparkapplication/skarkui.go" has regex as follow:
`var ingressURLRegex = regexp.MustCompile("{{\\s*[$]appName\\s*}}")`
as per this regex the matching value should be "{{\$appName\}}"

**Comment by mw-aftab** [comment] 2019-10-17 22:00
I found following related code changes.
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/200
and merge from Lyft "Operator State Management + Ingress Creation #291"

**Comment by mw-aftab** [comment] 2019-10-17 22:28
I was able to make UI work by "kubectl edit service spark-pi-ui-svc" and changing "type: ClusterIP" to "type: NodePort". But the change is in-memory only. Actual bug is still there in spark-operator and/or spark-operator chart.

**Comment by liyinan926** [comment] 2019-10-17 22:29
@akhurana001.

**Comment by akhurana001** [comment] 2019-10-18 00:21
@mw-aftab 

 I believe you will need to escape all the special chars. Also `ingressUrlFormat` is the correct key,

Can you try something like:
`helm install incubator/sparkoperator --name sparkoperator --namespace spark-operator --set enableWebhook=true  --set ingressUrlFormat="\{\{\$appName\}\}.ingress.cluster.com"`

**Comment by mw-aftab** [comment] 2019-10-18 02:00
Thank you @akhurana001. I no more seeing parser error. But spark-operator did not create ingress or opened NodePort when I deployed "spark-pi.yaml".  I am following https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/quick-start-guide.md.

here is my output
`
status:
  applicationState:
    state: COMPLETED
  driverInfo:
    podName: spark-pi-driver
    webUIAddress: 10.96.65.4:4040
    webUIIngressAddress: spark-pi.ingress.cluster.com
    webUIIngressName: spark-pi-ui-ingress
    webUIPort: 4040
    webUIServiceName: spark-pi-ui-svc
  executionAttempts: 1
`

**Comment by akhurana001** [comment] 2019-10-18 20:09
The Operator doesn't create a NodePort service. It creates a ClusterIp service with an optional ingress if you specify the ingress-address-format which it seems to be doing from the status you posted: `webUIIngressName: spark-pi-ui-ingress`. 

Also to clarify, the ingressUrlFormat expects that you have a ingress URL suffix for the cluster. So if you set something like ingressUrlFormat="\{\{\$appName\}\}.ingress.cluster.com", anything `*ingress.cluster.com` should be routed to the ingress-controller on the K8s cluster. Not sure where you are running but for e.g. In AWS, this can be done by creating a AWS Route 53 record of type CNAME which points to the node running ingress-controller (or ELB with nodes behind it).  More info here: [AWS resource-record-sets-creating](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resource-record-sets-creating.html). 

The value from 'ingressUrlFormat' is used by the SparkOperator to set the host value in[ name-based-virtual-hosting](https://kubernetes.io/docs/concepts/services-networking/ingress/#name-based-virtual-hosting): https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/pkg/controller/sparkapplication/sparkui.go#L71 


Because not every user will have this set-up, the Ingress Creation is optional.  If you don't have this set-up, you can skip ingress creation and use `kubectl port-forward` to look at the UI.

**Comment by mw-aftab** [comment] 2019-10-18 21:19
Thank you @akhurana001  for the  instructions. I will redeploy the operator as you described. I am deploying spark-operator on a two nodes local cluster.

**Comment by mw-aftab** [comment] 2019-10-20 00:38
I was able to access spark-pi-ui-svc UI using NodePort and port-forward methods.  I will request to update doc accordingly before closing this issue.

**Comment by akhurana001** [comment] 2019-10-21 18:53
Update the docs in https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/667 . Closing this out. Feel-free to let us know if there are any other questions.

**Comment by liyinan926** [comment] 2019-10-21 18:56
Thanks @akhurana001 for helping with this issue!

**Closed by liyinan926** 2019-10-21 18:56 UTC
