### ISSUE TITLE
When two spark applications are running, starting a third causes resubmission

### ISSUE THREAD

**Issue by ralphgonz** [GoogleCloudPlatform/spark-on-k8s-operator#197] opened 2018-06-27 17:27 UTC
Once we have already started two distinct spark applications A and B using spark operator (1 driver and 1 executor pod each), then starting a third distinct application C causes existing application B to be resubmitted. Spark operator then gives resubmitted application B the status: SUBMISSION_FAILED, even though the driver and executor pods for all three applications A, B, and C are still healthy and running with no restarts.

A few seconds after submitting application C, the spark operator log shows the following (where "baseline-calculation" is the name of application B):

```
$ kubectl logs blah-sparkoperator-56f7c7485b-fc459
...
E0627 16:29:31.262184       1 submission_runner.go:93] failed to run spark-submit for SparkApplication baseline-calculation in namespace ralph:
I0627 16:29:31.262261       1 controller.go:448] Not retrying submission of SparkApplication baseline-calculation

```

And here is the kubernetes log for application B:

```
$ kubectl describe sparkapplications baseline-calculation
...
Status:
  App Id:  baseline-calculation-2856396847
  Application State:
    Error Message:
    State:          SUBMISSION_FAILED
  Completion Time:  <nil>
  Driver Info:
    Pod Name:             baseline-calculation-b3d2427577173745b1fa542d47c90b87-driver
    Web UI Address:       10.128.11.237:32157
    Web UI Port:          32157
    Web UI Service Name:  baseline-calculation-2856396847-ui-svc
  Executor State:
    Baseline - Calculation - B 3 D 2427577173745 B 1 Fa 542 D 47 C 90 B 87 - Exec - 1:  RUNNING
  Submission Time:                                                                      2018-06-27T16:26:26Z
Events:
  Type     Reason                            Age   From            Message
  ----     ------                            ----  ----            -------
  Normal   SparkApplicationAdded             43m   spark-operator  SparkApplication baseline-calculation was added, enqueued it for submission
  Warning  SparkApplicationSubmissionFailed  40m   spark-operator  SparkApplication baseline-calculation failed submission:
```

This occurs consistently for a variety of namespaces and applications on our cluster. It appears that spark operator is automatically resubmitting an existing application and then giving it an incorrect status?

Are other people successfully using spark operator to start multiple distinct applications on the same cluster?

**Comment by liyinan926** [comment] 2018-11-20 19:15
Closing this as I couldn't reproduce it. Feel free to reopen if this issue still persists.

**Closed by liyinan926** 2018-11-20 19:15 UTC
