### ISSUE TITLE
Spark executors won't start

### ISSUE THREAD

**Issue by yuchaoran2011** [GoogleCloudPlatform/spark-on-k8s-operator#133] opened 2018-04-24 13:47 UTC
I have a docker image for a Spark 2.3 job that I could run successfully on Kubernetes using spark-submit. But when I started the job using the operator, the only things that got started were the driver pod and the UI svc, no Spark executors were launched. I didn't see any error in the sparkoperator pod and my app's driver pod. Anyone know what might be causing this issue? Btw, running the example spark-pi job using the operator works fine (executors got started etc).

**Comment by yuchaoran2011** [comment] 2018-04-24 13:48
I'd like to add a "Help wanted" label to this issue as recommended in  contributing guidelines, but apparently I don't have the permission to do that. I'd appreciate it if someone can do that.

**Comment by yuchaoran2011** [comment] 2018-04-24 16:07
Thanks for the reply. No, the executor pods were not created. Only the driver pod was there and running. I don’t remember seeing resource related messages in the logs. And running the app with spark-submit in the same cluster environment worked. I’ll double check later today to make sure this is the case.

**Comment by yuchaoran2011** [comment] 2018-04-24 17:42
Ok so I've verified it's not a resource issue. Here's the Spark-submit command I used that worked:

```bash
bin/spark-submit \
       --master k8s://http://10.0.6.184:9000 \
       --deploy-mode cluster \
       --files http://api.hdfs.marathon.l4lb.thisdcos.directory/v1/endpoints/hdfs-site.xml,http://api.hdfs.marathon.l4lb.thisdcos.directory/v1/endpoints/core-site.xml \
       --name killrweather \
       --class com.lightbend.killrweather.app.KillrWeather \
       --conf spark.executor.instances=3 \
       --conf spark.kubernetes.mountDependencies.filesDownloadDir=/etc/hadoop/conf \
       --conf 'spark.driver.extraJavaOptions=-Dconfig.resource=cluster.conf' \
       --conf spark.kubernetes.container.image=lightbend/killrweather:2.3.0 \
       --conf spark.kubernetes.container.image.pullPolicy=Always \
       local:///opt/spark/jars/killrWeatherApp-assembly-1.1.0.jar
```

When submitted the same job using the following operator YAML, the executor pods are not created at all.

```yaml
apiVersion: sparkoperator.k8s.io/v1alpha1
kind: SparkApplication
metadata:
 name: kw
 namespace: default
spec:
 type: Scala
 mode: cluster
 image: lightbend/killrweather:2.3.0
 mainClass: com.lightbend.killrweather.app.KillrWeather
 mainApplicationFile: local:///opt/spark/jars/killrWeatherApp-assembly-1.1.0.jar
 sparkConf:
     "spark.kubernetes.mountDependencies.filesDownloadDir": /etc/hadoop/conf
     "spark.driver.extraJavaOptions": -Dconfig.resource=cluster.conf
 deps:
     files:
       - http://api.hdfs.marathon.l4lb.thisdcos.directory/v1/endpoints/hdfs-site.xml
       - http://api.hdfs.marathon.l4lb.thisdcos.directory/v1/endpoints/core-site.xml
 executor:
     cores: 1
     instances: 3
     memory: 512m
     labels:
      version: 2.3.0
 driver:
     cores: 1
     memory: 512m
     serviceAccount: spark
     labels:
      version: 2.3.0
````

**Comment by liyinan926** [comment] 2018-04-24 17:48
Can you share your driver logs? I noticed you didn't specify the service account to use in the `spark-submit` case.

**Comment by yuchaoran2011** [comment] 2018-04-24 17:51
Sure the driver pod logs are in the file: [logs-from-spark-kubernetes-driver-in-kw-ed0fd6795eec36049f670d3e8378c7ed-driver.txt](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/files/1943957/logs-from-spark-kubernetes-driver-in-kw-ed0fd6795eec36049f670d3e8378c7ed-driver.txt)

**Comment by yuchaoran2011** [comment] 2018-04-24 18:07
I tried using `spec.dep.filesDownloadDir` in the YAML file as suggested, but nothing changed: The driver is still running but executors are nowhere to be seen.

**Comment by liyinan926** [comment] 2018-04-24 19:11
Can you check the directory `$SPARK_HOME/conf` and see if there's `log4j.properties`?

**Comment by yuchaoran2011** [comment] 2018-04-24 19:14
The image that I used `lightbend/killrweather:2.3.0` is in fact `FROM` your image: `gcr.io/ynli-k8s/spark:v2.3.0`. In that image, under the path `/opt/spark/conf`, no `log4j.properties` file exists. All there is is a bunch of template files.

**Comment by liyinan926** [comment] 2018-04-24 19:15
Another possibility is your application may container log4j configuration somewhere that overrides the default.

**Comment by kimoonkim** [comment] 2018-04-24 22:50
I think we should somehow support this use case, how to enable log4j DEBUG easily. I ran into this before and it's not fun to bake a new image just to enable DEBUG. Maybe we should support a `ConfigMap` volume containing `log4j.properties` and other files and mount them inside `/opt/spark/conf`.

**Comment by liyinan926** [comment] 2018-04-24 22:53
This is already supported. You can create a ConfigMap with a custom log4j.properties and then get it mounted with `spec.hadoopConfigMap`. This requires enabling the initializer though.

**Comment by kimoonkim** [comment] 2018-04-24 23:45
Ah, great to learn! Is this unique to this operator as opposed to the upstream spark?

**Comment by liyinan926** [comment] 2018-04-25 01:02
This is unique to the operator. However, the recent PR that removed the init-container in upstream also introduced an internally used ConfigMap that carries the Spark configuration properties in a file for the driver. This ConfigMap gets mounted to `/opt/spark/conf` and the environment variable `SPARK_CONF_DIR` is set to point to the mount path. This change makes it much harder for users to mount their own Spark ConfigMaps if not impossible.

**Comment by yuchaoran2011** [comment] 2018-04-25 03:05
It was indeed in our own configuration that the logging level was set to WARN. Due to a build issue I haven't been able to build a new image with a more verbose logging level. I'll report back here when I get more logs and if they reveal anything interesting. Unfortunately our cluster is not configurable to enable initializers.

**Comment by liyinan926** [comment] 2018-04-25 05:29
@yuchaoran2011 one thing you might want to check and share here is the `spark-submit` command the operator generated and ran for your job. This can be found in the operator logs that you can get from the operator pod.

**Comment by liyinan926** [comment] 2018-05-24 21:54
Have you figured out what's wrong? Can this be closed?

**Comment by yuchaoran2011** [comment] 2018-05-31 04:03
Sorry for the delay. I got back to working on this issue a few days ago and found that executors wouldn't start because my Spark streaming app didn't receive any messages from Kafka, although I did verify that there were messages coming through. The strange thing is that this only happened when the Spark streaming app was started using the Operator. It worked fine (i.e. getting messages from Kafka and then launching executors to perform computations) when the same code/docker image was started using spark-submit.

From the logs, I checked that both the operator and spark-submit passed almost identical parameters under the hood (except for a few operator-specific settings). Enabling DEBUG verbosity didn't help identify the problem either.

**Comment by yuchaoran2011** [comment] 2018-06-28 20:06
@liyinan926 Today we saw an error that explains why the executor pods won't start and why removing executor labels and annotations worked: 
```
ERROR Utils:91 - Uncaught exception in thread kubernetes-pod-allocator
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://kubernetes.default.svc/api/v1/namespaces/default/pods. Message: Pod "kw-95fbf753134f3bd9844c2704591e774c-exec-1" is invalid: [metadata.labels: Invalid value: "sparkoperator.k8s.\"io/app-id\"": prefix part a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.labels: Invalid value: "sparkoperator.k8s.\"io/app-id\"": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'), metadata.labels: Invalid value: "sparkoperator.k8s.\"io/launched-by-spark-operator\"": prefix part a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.labels: Invalid value: "sparkoperator.k8s.\"io/launched-by-spark-operator\"": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'), metadata.labels: Invalid value: "sparkoperator.k8s.\"io/app-name\"": prefix part a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.labels: Invalid value: "sparkoperator.k8s.\"io/app-name\"": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')]. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.labels, message=Invalid value: "sparkoperator.k8s.\"io/app-id\"": prefix part a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), reason=FieldValueInvalid, additionalProperties={}), StatusCause(field=metadata.labels, message=Invalid value: "sparkoperator.k8s.\"io/app-id\"": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'), reason=FieldValueInvalid, additionalProperties={}), StatusCause(field=metadata.labels, message=Invalid value: "sparkoperator.k8s.\"io/launched-by-spark-operator\"": prefix part a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), reason=FieldValueInvalid, additionalProperties={}), StatusCause(field=metadata.labels, message=Invalid value: "sparkoperator.k8s.\"io/launched-by-spark-operator\"": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'), reason=FieldValueInvalid, additionalProperties={}), StatusCause(field=metadata.labels, message=Invalid value: "sparkoperator.k8s.\"io/app-name\"": prefix part a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), reason=FieldValueInvalid, additionalProperties={}), StatusCause(field=metadata.labels, message=Invalid value: "sparkoperator.k8s.\"io/app-name\"": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'), reason=FieldValueInvalid, additionalProperties={})], group=null, kind=Pod, name=kw-95fbf753134f3bd9844c2704591e774c-exec-1, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Pod "kw-95fbf753134f3bd9844c2704591e774c-exec-1" is invalid: [metadata.labels: Invalid value: "sparkoperator.k8s.\"io/app-id\"": prefix part a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.labels: Invalid value: "sparkoperator.k8s.\"io/app-id\"": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'), metadata.labels: Invalid value: "sparkoperator.k8s.\"io/launched-by-spark-operator\"": prefix part a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.labels: Invalid value: "sparkoperator.k8s.\"io/launched-by-spark-operator\"": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'), metadata.labels: Invalid value: "sparkoperator.k8s.\"io/app-name\"": prefix part a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.labels: Invalid value: "sparkoperator.k8s.\"io/app-name\"": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')], metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:470)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:409)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:226)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:769)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:356)
	at org.apache.spark.scheduler.cluster.k8s.KubernetesClusterSchedulerBackend$$anon$1$$anonfun$3$$anonfun$apply$3.apply(KubernetesClusterSchedulerBackend.scala:134)
	at org.apache.spark.scheduler.cluster.k8s.KubernetesClusterSchedulerBackend$$anon$1$$anonfun$3$$anonfun$apply$3.apply(KubernetesClusterSchedulerBackend.scala:134)
	at org.apache.spark.util.Utils$.tryLog(Utils.scala:2001)
	at org.apache.spark.scheduler.cluster.k8s.KubernetesClusterSchedulerBackend$$anon$1$$anonfun$3.apply(KubernetesClusterSchedulerBackend.scala:133)
	at org.apache.spark.scheduler.cluster.k8s.KubernetesClusterSchedulerBackend$$anon$1$$anonfun$3.apply(KubernetesClusterSchedulerBackend.scala:132)
	at scala.collection.MapLike$MappedValues$$anonfun$foreach$3.apply(MapLike.scala:245)
	at scala.collection.MapLike$MappedValues$$anonfun$foreach$3.apply(MapLike.scala:245)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:99)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at scala.collection.MapLike$MappedValues.foreach(MapLike.scala:245)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.spark.scheduler.cluster.k8s.KubernetesClusterSchedulerBackend$$anon$1.run(KubernetesClusterSchedulerBackend.scala:139)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Looks like there is an unwanted quote in the label inserted by the operator. But from the operator code, I don't see such quote inserted anywhere. Do you have any suggestion why this is happening?

You can see the full logs at [kw.log](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/files/2146813/kw.log) and the YAML file that produced it: [deb.yaml](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/files/2146816/deb.yaml.txt). (Github didn't let me upload a YAML file, so I appended a txt suffix in the filename).

**Comment by yuchaoran2011** [comment] 2018-07-12 18:57
I should have provided an update. After rebuilding the Spark operator with Spark 2.3.1, this issue is fixed. I would leave this issue open though, until the root cause is found regarding why Spark 2.3.0 was not working.

**Comment by liyinan926** [comment] 2018-09-11 20:17
I'm going to close this. Please reopen if you figure out the root cause with 2.3.0.

**Closed by liyinan926** 2018-09-11 20:17 UTC
