### ISSUE TITLE
On forcefully deletion of a driver, the driver is not getting restarted.

### ISSUE THREAD

**Issue by suchitgupta01** [GoogleCloudPlatform/spark-on-k8s-operator#897] opened 2020-05-01 23:24 UTC
I have a spark streaming job that I am trying to submit by a spark-k8-operator. I have kept the restart policy as Always. However, on the manual deletion of the driver the driver is not getting restarted.
My yaml:
`
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: test-v2
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "com/test:v1.0"
  imagePullPolicy: Never
  mainClass: com.test.TestStreamingJob
  mainApplicationFile: "local:///opt/spark-2.4.5/work-dir/target/scala-2.12/test-0.1.jar"
  sparkVersion: "2.4.5"
  **restartPolicy:
    type: Always**
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 2.4.5
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
    terminationGracePeriodSeconds: 60
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    labels:
      version: 2.4.5
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
`
Spark version: 2.4.5
apiVersion: "sparkoperator.k8s.io/v1beta2"

**Steps which I followed:**
1. Create resource via kubectl apply -f examples/spark-test.yaml . Pod created successfully.
2. Delete the driver manually.

**Expected behavior:**
A new driver pod would be restarted as per the restart policy.

**Actual behavior:**
Driver and executor pods got deleted. 

**Environment:**
Testing out this with Docker On Mac. With 4 CPUs and 8 GB Memory

**Logs from spark -operator**
{FAILING driver pod failed with ExitCode: 143, Reason: Error}

**Comment by liyinan926** [comment] 2020-05-02 04:30
Can you check the status of your `SparkApplication` by doing `kubectl get sparkapplication <name> -o=yaml`?

**Comment by suchitgupta01** [comment] 2020-05-02 07:16
@liyinan926 
`
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"sparkoperator.k8s.io/v1beta2","kind":"SparkApplication","metadata":{"annotations":{},"name":"test-v2","namespace":"default"},"spec":{"driver":{"coreLimit":"1200m","cores":1,"labels":{"version":"2.4.5"},"memory":"512m","serviceAccount":"spark","terminationGracePeriodSeconds":60,"volumeMounts":[{"mountPath":"/tmp","name":"test-volume"}]},"executor":{"cores":1,"instances":2,"labels":{"version":"2.4.5"},"memory":"512m","volumeMounts":[{"mountPath":"/tmp","name":"test-volume"}]},"image":"com/test:v1.0","imagePullPolicy":"Never","mainApplicationFile":"local:///opt/spark-2.4.5/work-dir/target/scala-2.12/test-0.1.jar","mainClass":"com.test.TestStreamingJob","mode":"cluster","restartPolicy":{"type":"Always"},"sparkVersion":"2.4.5","type":"Scala","volumes":[{"hostPath":{"path":"/tmp","type":"Directory"},"name":"test-volume"}]}}
  creationTimestamp: "2020-05-01T08:12:09Z"
  generation: 4
  name: test-v2
  namespace: default
  resourceVersion: "37484"
  selfLink: /apis/sparkoperator.k8s.io/v1beta2/namespaces/default/sparkapplications/test-v2
  uid: 6eb1e6cc-4009-41e1-9dcc-f02fbf26baca
spec:
  driver:
    coreLimit: 1200m
    cores: 1
    labels:
      version: 2.4.5
    memory: 512m
    serviceAccount: spark
    terminationGracePeriodSeconds: 60
    volumeMounts:
    - mountPath: /tmp
      name: test-volume
  executor:
    cores: 1
    instances: 2
    labels:
      version: 2.4.5
    memory: 512m
    volumeMounts:
    - mountPath: /tmp
      name: test-volume
  image: com/test:v1.0
  imagePullPolicy: Never
  mainApplicationFile: local:///opt/spark-2.4.5/work-dir/target/scala-2.12/test-0.1.jar
  mainClass: com.test.TestStreamingJob
  mode: cluster
  restartPolicy:
    type: Always
  sparkVersion: 2.4.5
  type: Scala
  volumes:
  - hostPath:
      path: /tmp
      type: Directory
    name: test-volume
status:
  applicationState:
    errorMessage: 'driver pod failed with ExitCode: 143, Reason: Error'
    state: FAILING
  driverInfo:
    podName: test-v2-driver
    webUIAddress: 10.98.57.201:4040
    webUIPort: 4040
    webUIServiceName: test-v2-ui-svc
  executionAttempts: 1
  executorState:
    test-v2-1588402847814-exec-1: FAILED
    test-v2-1588402847814-exec-2: FAILED
  lastSubmissionAttemptTime: "2020-05-02T07:00:49Z"
  sparkApplicationId: spark-58491973c21f4585ae054b286c4d2c9f
  submissionAttempts: 1
  submissionID: 896d5184-ae44-4e87-bf05-45158f811640
  terminationTime: "2020-05-02T07:07:39Z"
`

**Comment by liyinan926** [comment] 2020-05-03 02:01
I think the problem is that you don't have retry limits and intervals defined under `restartPolicy`. There seems a bug in how default values of those get applied, causing the limits to be zeros if not specified. If you follow the following example, the operator should be able to restart the job automatically:

```yaml
spec:
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 3
    onSubmissionFailureRetryInterval: 10 
```

**Comment by liyinan926** [comment] 2020-05-03 02:08
In the meantime, I created #898 to fix the but with default values.

**Comment by suchitgupta01** [comment] 2020-05-03 20:09
@liyinan926 thanks!!

BTW what are the default values? 

Also, is it possible to keep the value of onFailureRetryInterval dynamic and let the code based on the exception set it?

I have a requirement where the target database might have a maintenance window and during that period I want to keep onFailureRetryInterval at a higher value. OR Can have a new flag which gets triggered based on application exit code? I want to handle database downtime with a higher retry interval.

**Comment by jkleckner** [comment] 2020-05-04 14:52
@suchitgupta01  Would using the `Always` policy with an exponential backoff to some maximum also fit your use case?

@liyinan926 Is there a way with the existing operator release to use `Always` and have it retry?

**Comment by liyinan926** [comment] 2020-05-04 17:04
@suchitgupta01 the default values are as follow:

```
restartPolicy:
  type: Never
  onFailureRetryInterval: 5 # seconds
  onSubmissionFailureRetryInterval: 5 # seconds
```

@jkleckner you can use `Always` to request retries with a linear backoff mechanism.

**Comment by jkleckner** [comment] 2020-05-04 17:10
@liyinan926 But the OP was already using `Always` and the retry didn't happen, true?
I guess my question is more clear as "Is there a workaround with the currently released operator to  retry on failure?"

**Comment by liyinan926** [comment] 2020-05-04 17:11
Yes, see https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/897#issuecomment-623042026.

**Comment by jkleckner** [comment] 2020-05-04 17:21
Sorry to be so imprecise.
I want something to always restart on success or failure.
This is what `Always` means, true?  And that didn't work for the OP.
So would something like this accomplish that?
```
restartPolicy:
  type: Always
  onFailureRetries: 1000000
  onFailureRetryInterval: 10
  onSubmissionFailureRetries: 3
  onSubmissionFailureRetryInterval: 10 
  ```

**Comment by liyinan926** [comment] 2020-05-04 17:25
Yes, that's supposed to work.

**Comment by suchitgupta01** [comment] 2020-05-05 01:59
@jkleckner @liyinan926 'exponential backoff' won't fit in my case. 
Use Case: If the database is down for maintenance, I was looking for a higher "onFailureRetryInterval" say 1 hour and in the normal case, it would be 30 seconds. 

Can we set the onFailureRetryInterval, on the basis of exit code like if System.exit(1) then we set a different value?

**Comment by liyinan926** [comment] 2020-05-05 16:25
@suchitgupta01 no, the operator doesn't setting `onFailureRetryInterval` adaptively at runtime.

**Comment by liyinan926** [comment] 2020-05-05 18:34
BTW: @suchitgupta01 have you tried the workaround above? If so, did it solve the issue of no auto restart?

**Comment by suchitgupta01** [comment] 2020-05-05 19:45
@liyinan926 thanks for the help. Tested both workaround and the fix. Working fine

**Comment by liyinan926** [comment] 2020-05-05 19:52
OK, closing this. As I said, the operator doesn't support setting `onFailureRetryInterval` adaptively at runtime.

**Closed by liyinan926** 2020-05-05 19:52 UTC

**Comment by amitme10** [comment] 2020-10-26 10:14
Hey @liyinan926 
Im using v1beta2-1.1.2-2.4.5 version  with those values for my streaming job :

```
  Restart Policy:
    On Failure Retries:                    1000000
    On Failure Retry Interval:             10
    On Submission Failure Retries:         1000000
    On Submission Failure Retry Interval:  10
    Type:                                  Always
```

Also I have this cronjob which delete the driver every hour - just to test how it deals with failure recovery and such.
and it works fine at the first , it takes it a few seconds to raise up again .
however after a few hours (12 h) I noticed that the raising up process isn't anymore a few seconds but a few minutes (5m), and it will keep increasing .

If I look at the operator logs Ill see the 143 error over there.

Do you know something about it ?
