### ISSUE TITLE
the operator is broken when using prometheus

### ISSUE THREAD

**Issue by EladDolev** [GoogleCloudPlatform/spark-on-k8s-operator#468] opened 2019-04-03 09:13 UTC
the config map for prometheus jmx exporter is not being mounted anymore
as a consequence the driver fail to start when using prometheus

commit `b8c7edca0eeb372fb68089b433d559f721734711` might have broken it

**Comment by liyinan926** [comment] 2019-04-03 17:30
@yuchaoran2011.

**Comment by yuchaoran2011** [comment] 2019-04-04 17:04
I just tried to submit a job using my custom Spark image and it worked fine. But running the job with `gcr.io/spark-operator/spark:v2.4.0-gcs-prometheus` image did produce an error in the driver pod. I don't think that commit you referred to is faulty though. The only relevant difference between my image and the gcr one is that my image has the following permission:
```
-rw-rw-r-- 1 root root 367417 Mar 22 02:42 jmx_prometheus_javaagent-0.3.1.jar
```
Whereas the gcr one has:
```
-rw------- 1 root root 367417 May 10  2018 jmx_prometheus_javaagent-0.3.1.jar
```
@EladDolev Can you check if your job is running as a non-root user? If so, that would explain it because the jar in the gcr image is only readable by root.

**Comment by EladDolev** [comment] 2019-04-07 08:43
I don't know about your image, and I can't use it without authorization
I'm trying with `v2.4.0-v1beta1-0.8.1` and `v2.4.0-v1beta1-latest` and as I said `/etc/metrics/conf` is not being mounted and I get 
`Caused by: java.io.FileNotFoundException: /etc/metrics/conf/prometheus.yaml (No such file or directory)`

we're actually using latest jar because 0.3.1 is very old
the configuration looks like this :
monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      port: 8090
      jmxExporterJar: "/opt/jmx_exporter/jmx_prometheus_javaagent.jar"
      configuration: |
{{ toYaml .Values.jmx_exporter_configuration | indent 8 }}`

we're also using our configuration because what is provided with spark operator is broken
I saw there was a commit to fix it, but it is still running with the old one, for example:
rules:
      - pattern: metrics<name=(\S+)\.(\S+)\.driver\.(BlockManager|DAGScheduler|jvm)\.(\S+)><>Value
        name: spark_driver_$3_$4
        type: GAUGE
        labels:
          app_namespace: "$1"
          app_id: "$2"

**Comment by yuchaoran2011** [comment] 2019-04-09 15:06
@EladDolev `prometheus.yaml` should have been put in your Spark image at path `/etc/metrics/conf` when you built it. Can you double check if your image has it? Refer to this [Dockerfile](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/spark-docker/Dockerfile#L31) for an example.

**Comment by yuchaoran2011** [comment] 2019-04-09 15:26
That explains why. You need the file in the image. 

If you don't want the file in the image, there are two options:
* `.spec.monitoring.prometheus.configuration` is still [valid](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/api.md#prometheusspec). But note that you need to put the **contents** of the Prometheus YAML file there, **not the path**. 
* If you want to put the path of the config file, then use `.spec.monitoring.prometheus.configFile`.

**Comment by EladDolev** [comment] 2019-04-09 15:29
We don't want the file in the image.
We are using `.spec.monitoring.prometheus.configuration`
This bug is about the new version not mounting the config map it creates from this field

**Comment by andrewgdavis** [comment] 2019-04-09 19:36
I had a similar problem... it used to be that metricsProperties was propagated (i couldn't find it in the container... for some reason it stopped working)... and so I ended up creating a configmap:
```
    configMaps:
      - name: promconf
        path: /etc/metrics/conf
```
that mounted the following files:
1. jmxCollector.yaml
2. metrics.properties
3. prometheus.yaml
Now, i have issues when trying to run as a non-root user though...

**Comment by andrewgdavis** [comment] 2019-04-12 17:40
I dug into this a bit more yesterday and this is what i found:
1.  only if .spec.monitoring.prometheus is specified will the $sparkJob-prom-conf configmap be created.
2.  if it is specified, the driver somehow fails to mount it.
3.  and if jmxExporterJar isn't specified in .spec.monitoring.prometheus, the logs report this error when starting the pod:
```
Error opening zip file or JAR manifest missing :
Error occurred during initialization of VM
```

**Comment by rjanovski** [comment] 2019-04-17 10:54
using the official image `gcr.io/spark-operator/spark:v2.4.0` and manually adding `/prometheus/jmx_prometheus_javaagent.jar`
still reports the prometheus.yml file missing with:
```
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: "/prometheus/jmx_prometheus_javaagent.jar"
      port: 8090
```

this was not the case a few operator versions ago. My sparkapplication just stopped working

**Comment by liyinan926** [comment] 2019-04-17 16:28
Looking into this.

**Comment by liyinan926** [comment] 2019-04-19 20:20
I found what the issue is. We recently changed the way the webhook works. It used to rely on annotations added by the submission to find things it needs to patch. The new way is the webhook actually gets the `SparkApplication` object for the driver/executor pod it tries to patch. However, the ConfigMap for Prometheus configuration is added at runtime into `.spec.driver.configMaps` and `.spec.executor.configMaps`. But the updated `SparkApplication` object is not written back to the API server, causing the webhook to miss the ConfigMap for Prometheus. I will fix it. Sorry for the trouble.

**Comment by liyinan926** [comment] 2019-04-21 20:53
The ConfigMap mounting issue has been resolved in #477. I will cut a new release with the fix.

**Closed** 2019-04-21 20:52 UTC
Labels: bug

**Comment by AceHack** [comment] 2020-07-06 18:17
I'm still having this issue with 1.1.2

**Comment by AceHack** [comment] 2020-07-06 18:29
This is how I finally got it working with the latest operator, I don't think this is documented anywhere.  The `monitoring.metricsPropertiesFile` is also required not just `monitoring.prometheus.configFile`

```
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    metricsPropertiesFile: /etc/metrics/conf/metrics.properties
    prometheus:
      jmxExporterJar: /prometheus/jmx_prometheus_javaagent-0.13.0.jar
      configFile: /etc/metrics/conf/prometheus.yaml
      port: 8090
```
