### ISSUE TITLE
Spark operator broke on March 1

### ISSUE THREAD

**Issue by EladDolev** [GoogleCloudPlatform/spark-on-k8s-operator#440] opened 2019-03-13 11:25 UTC
Hello there,

We're using `gcr.io/spark-operator/spark-operator:v2.4.0-v1beta1-latest` and the latest hash working for us is `5909b8e3bf817327a65ead7f8a89f04712dd4bff1ce56c6dd3a4c9d4fce2bdde` from 2019-01-31

With all other versions we're getting `"applicationState": {
            "errorMessage": "Driver Pod not found",
            "state": "RUNNING"
        }`
and are able to submit new applications, but not patching existing ones.

Has something changed in such a way we're now using it wrong ?

We're using the mutating admission webhook

Any chance you could also create tags for released versions so we're not forced using latest ?

Thanks !

**Comment by liyinan926** [comment] 2019-03-13 20:53
Thanks for reporting this. Can you elaborate on what you meant by `are able to submit new applications, but not patching existing ones`?

Regarding tags, yes, we will tag the images with the releases they are associated with from now on. I will push an image tagged `v1beta1-0.7-2.4.0` associated with release https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/releases/tag/v1beta1-0.7-2.4.0 to unblock you, while investigating the issue.

**Comment by liyinan926** [comment] 2019-03-13 21:00
FYI: I pushed image `gcr.io/spark-operator/spark-operator:v2.4.0-v1beta1-0.7`.

**Comment by EladDolev** [comment] 2019-03-13 21:17
Appreciate you tagging the image that works for us, this really helps !

We're using a Helm chart we wrote that uses the operator.
When deploying a new Helm release with a streaming spark application, the new driver and executors are running fine, but we immediately get the error posted above.
We use `kubectl patch` to update the image tag we use for the applications, but it has no effect with the newer versions, while with the working versions it causes the older application to terminate, and then the operator starts a new app with spark-submit.

Let me know if further explanation is needed.

**Comment by liyinan926** [comment] 2019-03-13 21:25
There were indeed some changes to 1) the way the webhook works and 2) how application state is tracked and surfaced. Looks like the issue reported above is related to those changes. If you can give the image `gcr.io/spark-operator/spark-operator:latest` starting a try, with a state without running applications, that would be great. Let me know if you still run into any issues.

**Comment by EladDolev** [comment] 2019-03-14 09:53
`gcr.io/spark-operator/spark-operator:latest` does not exist, `gcr.io/spark-operator/spark-operator:v2.4.0-v1beta1-0.7` is broken and `gcr.io/spark-operator/spark-operator:v2.4.0-v1beta1-latest` works

**Comment by liyinan926** [comment] 2019-03-14 14:31
What is broken in `gcr.io/spark-operator/spark-operator:v2.4.0-v1beta1-0.7`?

**Comment by EladDolev** [comment] 2019-03-14 14:50
Same problem I was mentioning here
Unable to redeploy using patch, and getting `"errorMessage": "Driver Pod not found"`

**Comment by liyinan926** [comment] 2019-03-14 14:51
OK, yes, `gcr.io/spark-operator/spark-operator:v2.4.0-v1beta1-0.7` has a bug that cause patch to not re-trigger a run of the updated app. That was fixed in `gcr.io/spark-operator/spark-operator:v2.4.0-v1beta1-latest`.

**Comment by skonto** [comment] 2019-03-15 19:41
i am hitting the same issue.

**Comment by skonto** [comment] 2019-03-15 19:47
@liyinan926 does that mean that `v1beta1-0.8.0-2.4.0` is buggy too? It seems so.

**Comment by liyinan926** [comment] 2019-03-15 20:08
The error `Driver Pod not found` happens when the `SparkApplication` has a driver name recorded in its status section but has not finished (i.e., `terminationTime` is zero), but no driver pod was found. Was the driver pod around when this error happened?

**Comment by skonto** [comment] 2019-03-15 20:15
@liyinan926 log here: https://gist.github.com/skonto/4a02eeab4fe1ca70e252703a4c26af69
To reproduce it i just submit the app and at submission time I just do an update to the spec with a different argument.

**Comment by liyinan926** [comment] 2019-03-15 20:22
Ah, ok. I see what's wrong here. When you edit a submitted app, the operator gets the update and will invalidate the current run and delete the driver pod of the current run. This will cause the error `Driver Pod not found` to happen because the driver pod has been deleted due to the update and invalidation. I will fix this. I agree that we should push for more integration tests.

**Comment by skonto** [comment] 2019-03-16 00:11
@liyinan926 yes the driver pod is dead but executor state changes trigger app status updates. 
So here: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/pkg/controller/sparkapplication/controller.go#L333 we need to check from which state the app is coming from. If the app is in invalidating state then we should refrain from setting the status to failing.

**Comment by liyinan926** [comment] 2019-03-16 00:26
The fix would to be avoid calling `updateAppStatus` when the app state is `Invalidating` or `PendingRerun`.

**Comment by skonto** [comment] 2019-03-16 01:11
I am wondering what will happen if  call to `syncSparkApplication` (B) is done in parallel with another that is already in `PendingRerun` state (A). I suspect that this line https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/pkg/controller/sparkapplication/controller.go#L505 may fail to delete the pods (call b) and a submission from call (A) will proceed. I think `validateSparkResourceDeletion` should also delete any pending pods as well, so that (B) can cleanup (A's) submission. Am I missing something?

**Closed** 2019-03-18 23:00 UTC
