### ISSUE TITLE
Pod Monitors fails with "resourceVersion for the provided watch is too old"

### ISSUE THREAD

**Issue by juvlarN** [GoogleCloudPlatform/spark-on-k8s-operator#188] opened 2018-06-14 07:59 UTC
I have started up the spark-operator yesterday and did not submit any applications. Today I've watched the log and saw that apparently the pod monitors are not running anymore. I attached the error messages below. Or are these messages just warnings and not a real issue? 

The image I use is `/gcr.io/spark-operator/spark-operator@sha256:70994af7bcdb636e6ba42f60479f189a8bdde85eed7b74cd3b554cf4a7e61fa8`, which is the latest image atm. We run Kubernetes 1.9.1.

```
I0613 13:36:26.326190       1 main.go:91] Starting the Spark operator
I0613 13:36:26.347498       1 crd.go:55] Creating CustomResourceDefinition sparkapplications.sparkoperator.k8s.io
I0613 13:36:26.863629       1 crd.go:55] Creating CustomResourceDefinition scheduledsparkapplications.sparkoperator.k8s.io
I0613 13:36:27.373052       1 controller.go:139] Starting the SparkApplication controller
I0613 13:36:27.473301       1 controller.go:145] Starting the workers of the SparkApplication controller
I0613 13:36:27.473412       1 controller.go:94] Starting the ScheduledSparkApplication controller
I0613 13:36:27.473489       1 submission_runner.go:61] Starting the spark-submit runner
I0613 13:36:27.473513       1 spark_pod_monitor.go:111] Starting the Spark Pod monitor
I0613 13:36:27.573626       1 controller.go:100] Starting the workers of the ScheduledSparkApplication controller
W0613 13:44:28.440483       1 reflector.go:341] k8s.io/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1alpha1.SparkApplication ended with: The resourceVersion for the provided watch is too old.
W0613 13:46:09.425066       1 reflector.go:341] k8s.io/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1alpha1.ScheduledSparkApplication ended with: The resourceVersion for the provided watch is too old.
W0613 13:57:05.535917       1 reflector.go:341] k8s.io/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1alpha1.SparkApplication ended with: The resourceVersion for the provided watch is too old.
W0613 13:58:26.487098       1 reflector.go:341] k8s.io/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1alpha1.ScheduledSparkApplication ended with: The resourceVersion for the provided watch is too old.
W0613 14:05:02.510322       1 reflector.go:341] k8s.io/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1alpha1.ScheduledSparkApplication ended with: The resourceVersion for the provided watch is too old.
W0613 14:09:34.623918       1 reflector.go:341] k8s.io/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1alpha1.SparkApplication ended with: The resourceVersion for the provided watch is too old.
W0613 14:21:17.628619       1 reflector.go:341] k8s.io/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1alpha1.ScheduledSparkApplication ended with: The resourceVersion for the provided watch is too old.
W0613 14:22:50.700289       1 reflector.go:341] k8s.io/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1alpha1.SparkApplication ended with: The resourceVersion for the provided watch is too old.
W0613 14:30:03.707593       1 reflector.go:341] k8s.io/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1alpha1.ScheduledSparkApplication ended with: The resourceVersion for the provided watch is too old.
W0613 14:32:10.745838       1 reflector.go:341] k8s.io/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1alpha1.SparkApplication ended with: The resourceVersion for the provided watch is too old.
W0613 14:40:35.802946       1 reflector.go:341] k8s.io/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1alpha1.ScheduledSparkApplication ended with: The resourceVersion for the provided watch is too old.
W0613 14:42:03.765779       1 reflector.go:341] k8s.io/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1alpha1.SparkApplication ended with: The resourceVersion for the provided watch is too old.
W0613 14:49:03.857615       1 reflector.go:341] k8s.io/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1alpha1.ScheduledSparkApplication ended with: The resourceVersion for the provided watch is too old.
W0613 14:55:38.877650       1 reflector.go:341] k8s.io/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1alpha1.SparkApplication ended with: The resourceVersion for the provided watch is too old.
W0613 15:05:06.951222       1 reflector.go:341] k8s.io/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1alpha1.ScheduledSparkApplication ended with: The resourceVersion for the provided watch is too old.
W0613 15:11:27.954552       1 reflector.go:341] k8s.io/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1alpha1.SparkApplication ended with: The resourceVersion for the provided watch is too old.
W0613 15:14:36.009698       1 reflector.go:341] k8s.io/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1alpha1.ScheduledSparkApplication ended with: The resourceVersion for the provided watch is too old.
W0613 15:23:24.022060       1 reflector.go:341] k8s.io/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1alpha1.SparkApplication ended with: The resourceVersion for the provided watch is too old.
W0613 15:29:31.105577       1 reflector.go:341] k8s.io/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1alpha1.ScheduledSparkApplication ended with: The resourceVersion for the provided watch is too old.
W0613 15:32:04.095643       1 reflector.go:341] k8s.io/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1alpha1.SparkApplication ended with: The resourceVersion for the provided watch is too old.
W0613 15:39:01.167150       1 reflector.go:341] k8s.io/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1alpha1.ScheduledSparkApplication ended with: The resourceVersion for the provided watch is too old.
W0613 15:41:58.193935       1 reflector.go:341] k8s.io/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1alpha1.SparkApplication ended with: The resourceVersion for the provided watch is too old.
W0613 15:51:45.303965       1 reflector.go:341] k8s.io/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1alpha1.SparkApplication ended with: The resourceVersion for the provided watch is too old.
W0613 15:54:56.268178       1 reflector.go:341] k8s.io/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1alpha1.ScheduledSparkApplication ended with: The resourceVersion for the provided watch is too old.
W0613 16:00:00.318251       1 reflector.go:341] k8s.io/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1alpha1.SparkApplication ended with: The resourceVersion for the provided watch is too old.
W0613 16:09:56.367362       1 reflector.go:341] k8s.io/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1alpha1.SparkApplication ended with: The resourceVersion for the provided watch is too old.
W0613 16:13:11.330344       1 reflector.go:341] k8s.io/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1alpha1.ScheduledSparkApplication ended with: The resourceVersion for the provided watch is too old.
W0613 16:21:32.354376       1 reflector.go:341] k8s.io/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1alpha1.ScheduledSparkApplication ended with: The resourceVersion for the provided watch is too old.
W0613 16:25:00.435183       1 reflector.go:341] k8s.io/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1alpha1.SparkApplication ended with: The resourceVersion for the provided watch is too old.

```

**Comment by liyinan926** [comment] 2018-06-14 13:39
This is just a warning. I saw this a couple of times. It should affect the functioning of the operator.

**Comment by liyinan926** [comment] 2018-06-18 08:01
Closing this. Please reopen if this is causing real problems.

**Closed by liyinan926** 2018-06-18 08:01 UTC

**Comment by skonto** [comment] 2019-10-05 19:25
@liyinan926 I see the same on Openshift 3.11 with the same frequency:
```
W1005 18:41:31.150678      11 reflector.go:256] github.com/GoogleCloudPlatform/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1beta2.ScheduledSparkApplication ended with: The resourceVersion for the provided watch is too old.
W1005 18:48:27.390968      11 reflector.go:256] github.com/GoogleCloudPlatform/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1beta2.SparkApplication ended with: The resourceVersion for the provided watch is too old.
W1005 18:51:04.177578      11 reflector.go:256] github.com/GoogleCloudPlatform/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1beta2.ScheduledSparkApplication ended with: The resourceVersion for the provided watch is too old.
W1005 18:55:22.484770      11 reflector.go:256] github.com/GoogleCloudPlatform/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1beta2.SparkApplication ended with: The resourceVersion for the provided watch is too old.
W1005 19:06:45.231275      11 reflector.go:256] github.com/GoogleCloudPlatform/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1beta2.ScheduledSparkApplication ended with: The resourceVersion for the provided watch is too old.
W1005 19:11:20.609548      11 reflector.go:256] github.com/GoogleCloudPlatform/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: watch of *v1beta2.SparkApplication ended with: The resourceVersion for the provided watch is too old.
```
Also I read here as you mentioned it is not a bug: https://bugzilla.redhat.com/show_bug.cgi?id=1573460 but it really messes the logs. Any idea why this happens so often? Is it because of inactivity?
